### ISSUE TITLE
Bug: unable to access the login page after django upgrade

### ISSUE THREAD

**Issue by aminur80** [muccg/angelman#280]
**Description:**
When the user browse for angelman at http://localhost:8000, there is error shown in the browser

**Steps to reproduce:**
1) make sure the system is up and running
2) Open the browser and type http://localhost:8000
3) The browser comes up with the following error message - 
`django.urls.exceptions.NoReverseMatch
django.urls.exceptions.NoReverseMatch: 'two_factor' is not a registered namespace` 

**Expected Result:**
It should redirect to login page

**Comment by id2359** [comment]
app_name issue in base rdrf urls.pu
