### ISSUE TITLE
Bug: Unable to access login page after selecting the registry

### ISSUE THREAD

**Issue by aminur80** [muccg/angelman#281]
**Description:**
At rdrf landing page, when the user select the sample registry for login an error is shown.

**Steps to reproduce:**

1) Open the browser and type http://localhost:8000
2) Click on the registries on this site 
3) Then select Sample Registry (first time)
4) Then we see the following error in the browser
`django.urls.exceptions.NoReverseMatch
django.urls.exceptions.NoReverseMatch: Reverse for 'javascript-catalog' not found. 'javascript-catalog' is not a valid view function or pattern name.`

**Expected Result:**
It should redirect to login page

**Comment by id2359** [comment]
app_name issue in base rdrf urls.py
