### ISSUE TITLE
Bug: Landing page not displayed at the beginning

### ISSUE THREAD

**Issue by aminur80** [muccg/angelman#283]
**Description:**
When accessing the http://localhost:8000 for angelman, the landing page is not displayed

**Steps to follow:**
1) Go to http://localhost:8000
2) It gives the following error

`django.urls.exceptions.NoReverseMatch: Reverse for 'landing' not found. 'landing' is not a valid view function or pattern name.`

Expected Result:
The landing page should be viewed.

**Comment by aminur80** [comment]
in the index.html use rdrf app_name (which is rdrf before the landing url name)
<a href="{% url 'rdrf:landing' %}" class="navbar-brand">RDRF {% version_number %}</a>

**Comment by id2359** [comment]
Fixed by removing app_name from urls.py in base rdrf
