### ISSUE TITLE
bug: unable to start the login page

### ISSUE THREAD

**Issue by aminur80** [muccg/angelman#284]
Description:
At rdrf landing page, when the user select the sample registry for login an error is shown.

Steps to reproduce:

Open the browser and type http://localhost:8000
Click on the registries on this site
Then select Sample Registry (first time)
Then we see the following error in the browser
`django.urls.exceptions.NoReverseMatch
django.urls.exceptions.NoReverseMatch: Reverse for 'login_router' not found. 'login_router' is not a valid view function or pattern name.`

Expected Result:
It should redirect to login page

**Comment by id2359** [comment]
Fixed by removing app_name from base rdrf urls.py which was incorrect
