### ISSUE TITLE
Survey login results in 404

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/angelman#323]
Logging in to an email survey as a parent, with one child, with some clinical data entered, results in a 404 error. At least four different parents tested.
[Link to survey.](
https://rdrf.ccgapps.com.au/angelman/actions/action=survey&registry=ang&name=commsurvey "Survey link")
```
Page not found (404)

Request Method: 	GET
Request URL: 	https://rdrf.ccgapps.com.au/angelman/actions/action%3Dsurvey&registry%3Dang&name%3Dcommsurvey

```

**Comment by id2359** [comment]
bad url should be actions?
